config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'login' => 'login#new'
  get 'signup' => 'signup#new'
  get 'logout' => 'logout#destroy'

  post 'login' => 'login#create'
  post 'signup' => 'signup#create'

  get 'settings' => 'home#edit'
  post 'settings' => 'home#update'

  get 'organizations' => 'organizations#index'

  get 'organizations/new' => 'organizations#new'
  post 'organizations/new' => 'organizations#create'
  get 'organizations/:id' => 'organizations#show'
  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_cookies
    session[:auth_token] = cookies.signed[:auth_token] if !cookies.signed[:auth_token].nil?
    session[:id] = cookies.signed[:id] if !cookies.signed[:id].nil?
  end

  def check_logged
    get_cookies
    redirect_to :login if session[:auth_token].nil?
  end

  def check_not_logged
    get_cookies
    redirect_to :root if !session[:auth_token].nil?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :check_logged

  def initialize
    super
    @api = Faraday.new(:url => 'http://api.meetable.fr') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
    end
  end

  def index
    response = @api.get("/users/#{session[:id]}", { auth_token: session[:auth_token] })
    if response.status == 200
      @result = JSON.parse(response.body).with_indifferent_access
    else
      flash[:alert] = 'Api request failed'
    end
  end

  def edit
  end

  def update
    args = {}
    p params
    args[:auth_token] = session[:auth_token]
    if !params[:login].blank?
      args[:login] = params[:login]
    end
    if !params[:email].blank?
      args[:email] = params[:email]
    end
    if !params[:password].blank?
      args[:password] = params[:password]
    end
    response = @api.put("/users/#{session[:id]}", args)
    result = JSON.parse(response.body).with_indifferent_access
    if response.status == 200
      flash[:success] = "Data successfully saved"
      redirect_to :settings
    else
      flash[:alert] = result[:error]
      redirect_to :settings
    end
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  before_action :check_not_logged
  
  def initialize
    super
    @api = Faraday.new(:url => 'http://api.meetable.fr') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
    end
  end

  def new
  end

  def create
    response = @api.post('/signin', login_params)
    result = JSON.parse(response.body).with_indifferent_access
    if response.status == 200
      session[:auth_token] = result[:auth_token]
      session[:id] = result[:id]
      cookies.permanent.signed[:auth_token] = result[:auth_token]
      cookies.permanent.signed[:id] = result[:id]
      redirect_to :root
    else
      flash.now[:alert] = result[:error]
      render :new
    end
  end

  def login_params
    params.permit(:login, :password)
  end

end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController

  def destroy
    session.delete(:auth_token)
    session.delete(:id)
    cookies.delete :auth_token
    cookies.delete :id
    redirect_to :root
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def initialize
    super
    @api = Faraday.new(:url => 'http://api.meetable.fr') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
    end
  end

  def index
    response = @api.get("/organizations", { auth_token: session[:auth_token] })
    if response.status == 200
      @organizations = JSON.parse(response.body)
    else
      flash[:alert] = 'Api request failed'
      redirect_to :logout
    end
  end

  def show
  end

  def new
  end

  def create
    args = {}
    p params
    args[:auth_token] = session[:auth_token]
    if !params[:name].blank?
      args[:name] = params[:name]
    end
    if !params[:description].blank?
      args[:description] = params[:description]
    end
    response = @api.post("/organizations", args)
    result = JSON.parse(response.body).with_indifferent_access
    if response.status == 200
      flash[:success] = "Data successfully saved"
      redirect_to :organizations
    else
      flash[:alert] = result[:error]
      redirect_to :organizations_new
    end
  end

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController

  before_action :check_not_logged

  def initialize
    super
    @api = Faraday.new(:url => 'http://api.meetable.fr') do |faraday|
      faraday.request  :url_encoded
      faraday.response :logger
      faraday.adapter  Faraday.default_adapter
    end
  end

  def new
  end

  def create
    response = @api.post('/users', signup_params)
    result = JSON.parse(response.body).with_indifferent_access
    if response.status == 200
      session[:auth_token] = result[:auth_token]
      session[:id] = result[:id]
      cookies.permanent.signed[:auth_token] = result[:auth_token]
      cookies.permanent.signed[:id] = result[:id]
      redirect_to :root
    else
      flash.now[:alert] = result[:error]
      render :new
    end

  end

  def signup_params
    params.permit(:login, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/home/edit.html.erb
<div class="row">
  <h2>Edit profile</h2>
  <div class="large-12 columns">
    <%= form_tag(controller: "home", action: "update") do %>
    <%= text_field_tag :login, nil, placeholder: "Login", class: "large-12" %>
    <%= email_field_tag :email, nil, placeholder: "E-mail", class: "large-12" %>
    <%= password_field_tag :password, nil, placeholder: "Password", class: "large-12" %>
    <%= submit_tag "Save", class: "button expand" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<button href="#" data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="button dropdown right small-12 large-1 columns">
  <%= @result[:login] %>
</button><br>
<ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
  <li><%= link_to "Edit profile", settings_path %></li>
  <li><%= link_to "Logout", logout_path %></li>
</ul>

<div class="row">
  <div class="large-7 large-centered columns">
    <%= image_tag "logo.png" %>
  </div>
</div>

<div class="pannel callout small-8 small-centered columns">
  "Meetable est une solution permettant d’améliorer les réunions. Elle se compose d’un ordinateur connecté à un projecteur qui affiche des informations sur une table quelconque. Chacun peut intéragir dans la réunion grâce à la reconnaissance de mouvements. En cas d’absence, la réunion peut être suivi depuis un smartphone."
</div>

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="small-12 columns">
    <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div class="hide-for-large-up">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="#">Meetable</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Organizations", root_path %></li>
	<li><%= link_to "Meetings", root_path %></li>
	<li class="active"><%= link_to "Logout", logout_path %></li>
      </ul>
    </section>
  </nav>
</div>

<ul id="mymenu" class="show-for-large-up large-2 columns menu vertical">
  <li><%= link_to "Home", root_path, class: "button midnight" %></li>
  <li><%= link_to "Organizations", organizations_path, class: "button midnight" %></li>
  <li><%= link_to "Meetings", root_path, class: "button midnight" %></li>
  <li><%= link_to "Logout", logout_path, class: "button" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Meetable" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if !session[:auth_token].nil? %>
    <div class="large-12 columns page">
      <%= render 'layouts/menu' %>
      <div class="large-10 columns">
	<%= render 'layouts/flash' %>
	<%= yield %>
      </div>
    </div>
    <% else %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <% end %>
  </body>
</html>

app/views/login/new.html.erb
<div class="row">
  <div class="large-7 large-centered columns">
    <%= image_tag "logo.png" %>
  </div>
</div>

<div class="row">
  <div class="large-6 large-centered columns">
    <div class="login-box">
      <div class="row">
	<div class="large-12 columns">
	  <%= form_tag(controller: "login", action: "create") do %>
	  <%= text_field_tag :login, nil, placeholder: "Login", class: "large-12" %>
	  <%= password_field_tag :password, nil, placeholder: "Password", class: "large-12" %>
	  <%= submit_tag "Login", class: "button expand" %>
	  <% end %>
	  <%= link_to "Sign Up", signup_path, class: "right" %>
	</div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/index.html.erb
<div class="row">
  <div class="large-12 large-centered columns">
    <div class="large-4 large-centered columns">
      <%= link_to "Create an organization", organizations_new_path, class: "button large-12 columns" %>
    </div>
    <div class="large-8 large-centered columns">
      <% @organizations.each do |organization| %>
      <%= link_to organization['name'], "#{organizations_path}/#{organization['id']}", class: "button midnight large-12 columns list-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="row">
  <h2>Create organization</h2>
  <div class="large-12 columns">
    <%= form_tag(controller: "organizations", action: "create") do %>
    <%= text_field_tag :name, nil, placeholder: "Name", class: "large-12" %>
    <%= text_field_tag :description, nil, placeholder: "Description", class: "large-12" %>
    <%= submit_tag "Create", class: "button expand" %>
    <% end %>
  </div>
</div>

app/views/signup/new.html.erb
<div class="row">
  <div class="large-7 large-centered columns">
    <%= image_tag "logo.png" %>
  </div>
</div>

<div class="row">
  <div class="large-6 large-centered columns">
    <div class="login-box">
      <div class="row">
	<div class="large-12 columns">
	  <%= form_tag(controller: "signup", action: "create", method: "post") do %>
	  <%= text_field_tag :login, nil, placeholder: "Login", class: "large-12" %>
	  <%= email_field_tag :email, nil, placeholder: "E-mail", class: "large-12" %>
	  <%= password_field_tag :password, nil, placeholder: "Password", class: "large-12" %>
	  <%= submit_tag "Login", class: "button expand" %>
	  <% end %>
	  <%= link_to "Login", login_path, class: "right" %>
	</div>
      </div>
    </div>
  </div>
</div>